import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * Main application window containing a single button.
 * <p>
 * When the button is clicked, its text changes from
 * "click me" to "Good job".
 */
public class MainWindow extends JFrame implements ActionListener {
    /** Button displayed in the window. */
    private JButton button;

    /**
     * Constructs the main window.
     * <p>
     * Initializes the frame size, layout, close operation,
     * creates the button, registers the action listener,
     * and makes the window visible.
     */
    MainWindow() {
        setSize(300, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new FlowLayout());
        button = new JButton("click me");
        add(button);

        button.addActionListener(this);

        setVisible(true);
    }

     /**
     * Handles button click events.
     * <p>
     * When triggered, updates the button text to "Good job".
     *
     * @param e the action event generated by the button click
     */
    public void actionPerformed(ActionEvent e) {
        button.setText("Good job");
    }
}
